# Created By Rahul Ranjan on 26/08/2018.
import os

path1 = os.path.dirname(__file__)
print("Path1", path1)

apiBodyDict = {
    'None': None,
    'CreatePromoRelianceRetail':
        {
            "promotions": [
                {
                    "REF_ID": "589663978",
                    "PROMO_NAME": "Dinner at Lotus with 50% discount",
                    "FORMAT": "FOOTPRINT",
                    "PROMO_STATUS": "Approved",
                    "PROMO_CREATION_DATE": "2018-05-08 00:00:00",
                    "START_DATE": "2015-01-17 00:00:00",
                    "END_DATE": "2019-01-19 00:00:00",
                    "PROMO_TYPE": "Normal Promotion",
                    "STORE_ID": [
                        "10001",
                        "11114"
                    ],
                    "TRIG_TYPE": "Quantity",
                    "TRIG_VAL": 1,
                    "ENTITY": [
                        {
                            "ID": "490009776",
                            "NAME": "Reebok Shoes",
                            "CATEGORIES": [
                                "Sports",
                                "Footware"
                            ]
                        },
                    ],
                    "ARTICLE_STATUS": "Include",
                    "REWARD_TYPE": "On Item New Price",
                    "PROMO_DESC": "Best Price",
                    "TRANSACTION_LIMIT": 12,
                    "LEVEL_REWARD_VAL": [
                        {
                            "REWARD_VAL1": 10,
                            "LEVEL_TRIG_VAL": 0
                        },
                        {
                            "REWARD_VAL1": 20,
                            "LEVEL_TRIG_VAL": 1
                        }
                    ],
                    "COUPON_TYPE": "No Coupon",
                    "SKU_OFFER_DATA": [
                        {
                            "SKU_ID": "123",
                            "NAME": "SOAP",
                            "QUANTITY": 10,
                            "COUPON_OFFER": 5
                        },
                        {
                            "SKU_ID": "234",
                            "NAME": "SOAP",
                            "QUANTITY": 10,
                            "COUPON_OFFER": 5
                        }
                    ],
                    "SKU_CONDITION_DATA": [
                        {
                            "SKU_ID": "123",
                            "NAME": "SOAP",
                            "QUANTITY": 10,
                            "COUPON_CONDITION": 5
                        },
                        {
                            "SKU_ID": "234",
                            "NAME": "SOAP",
                            "QUANTITY": 10,
                            "COUPON_CONDITION": 5
                        }
                    ],
                    "DOSCOUNT_PERCENTAGE_VAL": 10,
                    "DOSCOUNT_ABSOLUTE_VAL": 250,
                    "DOSCOUNT_MIN_BILL": 500,
                    "COUPON_SERIES_NO": "1234",
                    "TNC": "Free Text"
                }
            ]
        },

    'couponCampaignCreation' :
        {
            "name": "TestAutomation1",
            "startTime": "2018-06-23 00:00:00",
            "endTime": "2018-06-30 23:59:59",
            "userGroup": "42",
            "lineItems": [
                {
                    "coupons": [
                        2621,
                        3130
                    ],
                    "segment": {
                        "op": "and",
                        "segments": [
                            {
                                "op": "all",
                                "segments": []
                            }
                        ]
                    }
                }
            ]
        },
    'coupon_campaign_for_targeting':
        {
            "name": "test",
            "startTime": "2019-04-05 00:00:00",
            "endTime": "2019-04-30 23:59:59",
            "lineItems": [
                {
                    "coupons": [],
                    "segment": {
                        "op": "and",
                        "segments": [
                            {
                                "op": "not",
                                "segments": []
                            }
                        ]
                    }
                },
                {
                    "coupons": [],
                    "segment": {
                        "op": "and",
                        "segments": [
                            {
                                "op": "not",
                                "segments": []
                            }
                        ]
                    }
                }
            ],
        },
    'file_convertPromoToCoupon': {
        'file': ('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },

    'data_convertPromoToCoupon' : {
        'promoList[]':['36003','36005'],
        'clientList[]': ['2'],
    },
    'mapCouponCodeToPromo': {
        'file': ('couponcode.csv', open(path1 +"/files/couponcode.csv",'rb'), 'text/csv')
    },
    'redeemCoupon': {
        'file': ('redemptions.csv', open(path1 +"/files/redemptions.csv",'rb'), 'text/csv')
    },
    'file_add_merchants': {
    'image': ('jacoco.png', open(path1 + '/images/C.jpg','rb'), 'image/png')
    },
    'data_add_merchants': {
        "traits": "false",
        "isRRMerchant": "false",
        "name": "RR_merchant_bangalore_1",
        "cin": "L12345AA1234AAA123457",
        "url": "https://www.google.com",
        "masId": "ASDPR891999",
        "representative": "JIOMONEY",
        "phone": "9945340313",
        "email": "jiomoney@gmail.com",
        "subscribe": "true",
        "status": "approve",
        "username": "RR_merchant_bangalore_1",
        "userGroup": "42",
        "password": "cee3dc4d010c77d0041bd1e49a39630918559340cc7539d35d318b7f1de8cf02"
    },
    'file_add_branches': {
        'file': ('address_info.csv', open(path1+'/files/address_info.csv','rb'), 'text/csv')
    },
    'data_add_branches': {
        "traits": "false",
        "isRRMerchant": "false",
    },
    'data_merchant_branch_regular':
        {
            "merchant": '1083',
            "shopNumber": '1',
            "branchCode": 'kormangala',
            "branchName": 'kormangala',
            "zone": "kormangala",
            "state": "kormangala",
            "city": "kormangala",
            "locality": "kormangala",
            "address": "kormangala",
            "landmark": "kormangala",
            "pin": "560034",
            "latitude": "12.77777",
            "longitude": "33.222222",
            "status": "approve"
        },
    'create_merchant_group': {
        "name":"Test_Merchant_group",
        "desc":"Test_Group",
        "idList":[2088,2089,2090],
        "userGroup":"42"
    },
    'file_add_coupon_pull_merchant_type_flat_discount': {
        'file': ('A.jpg', open(path1 + '/images/A.jpg', 'rb'), 'image/jpeg'),
    },
    'data_add_coupon_pull_merchant_type_flat_discount': {
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "1|2|3|4|5|6",
        "couponType": "1",
        "clients[]": ["2","1"],
        "skuConditionType": "1",
        "skuOfferType": "1",
        "discountType": "FLAT_DISCOUNT",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "discountMinBill":"100",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|3|12|11",
        "title": "10 rs discount on 100 rs bill",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "2",
        "source": "prime",
        "merchant": "6184",
        "startDate": "2018/08/12",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Rs. 100 discount on a minimum purchase of Rs. 1000",
        "terms":"Rs. 100 discount on a minimum purchase of Rs. 1000",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup":"42"

    },
    'file_add_coupon_pull_merchant_type_Free_SKUs_on_Bill': {
        'file': ('A.jpg', open(path1 + '/images/A.jpg', 'rb'), 'image/jpeg'),
    },
    'data_add_coupon_pull_merchant_type_Free_SKUs_on_Bill': {
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "1",
        "redeemGender": "MALE",
        "locations": "1|2|3",
        "couponType": "1",
        "clients[]": "2",
        "skuConditionType": "1",
        "skuOfferType": "1",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|202|3|12|11",
        "title": "Bill Rs. 1000 get a 2kg tide pack",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "3",
        "source": "prime",
        "merchant": "6184",
        "discountType": "FREE_SKU_WITH_BILL",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "skuOffer": "10036387 |10036553",
        "skuOfferName": "Rs.30 off on buying 2 Tide Naturals 800g",
        "skuOfferQuantity": "1",
        "discountMinBill": "100",
        "skuConditionSellingPrice": "110",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup": "42"

    },
    'file_add_coupon_pull_merchant_type_Free_SKUs_on_SKUs':{
        'file': ('A.jpg', open(path1 + '/images/A.jpg', 'rb'), 'image/jpeg'),
    },
    'data_add_coupon_pull_merchant_type_Free_SKUs_on_SKUs':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "1|2|3|4|5|6",
        "couponType": "1",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|202|3|12|11",
        "title": "free tide with 1kg ariel",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "discover",
        "merchant": "6184",
        "clients[]": ["2","1"],
        "skuConditionType": "1",
        "skuOfferType": "1",
        "discountType": "FREE_SKU_WITH_SKU",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "skuCondition": "10050432|10046238| 10050432|10046238| 10036387| 10036553",
        "skuOffer":"10050432 | 10046238",
        "skuOfferName":"Tide Bar",
        "skuOfferQuantity":"1",
        "skuConditionName": "Pantene Total Damage Control 80ml",
        "skuConditionQuantity": "2",
        "skuConditionActualPrice": "100",
        "skuConditionSellingPrice": "110",
        "startDate": "2018/08/12",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Rs. 100 discount on a minimum purchase of Rs. 1000",
        "terms":"Rs. 100 discount on a minimum purchase of Rs. 1000",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup": "42"

    },
    'file_add_coupon_pull_merchant_type_flat_discount_on_sku': {
        'file': ('A.jpg', open(path1 + '/images/A.jpg', 'rb'), 'image/jpeg'),
    },
    'data_add_coupon_pull_merchant_type_flat_discount_on_sku': {
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "1|2|3|4|5|6",
        "couponType": "1",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|202|3|12|11",
        "title": "10rs off on tide natural",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "discover",
        "merchant": "6184",
        "discountType": "FLAT_DISCOUNT_WITH_SKU",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "clients[]": "2",
        "skuConditionType": "1",
        "skuOfferType": "1",
        "skuCondition": "10050432|10046238| 10050432|10046238| 10036387| 10036553",
        "skuConditionName": "Rs.30 off on buying 2 Tide Naturals 800g",
        "skuConditionQuantity": "1",
        "skuConditionActualPrice": "100",
        "skuConditionSellingPrice": "110",
        "startDate": "2018/08/12",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Rs. 100 discount on a minimum purchase of Rs. 1000",
        "terms":"Rs. 100 discount on a minimum purchase of Rs. 1000",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup": "42"

    },
    'file_add_coupon_pull_merchant_type_Percentage_discount_on_SKU':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_pull_merchant_type_Percentage_discount_on_SKU':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "1|2|3|4|5|6",
        "couponType": "1",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "title": "10% off on tide natural",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "discover",
        "merchant": "6184",
        "discountType": "PERCENTAGE_DISCOUNT_WITH_SKU",
        "discountExtraRules": "12",
        "clients[]": ["2","1"],
        "categories": "2|3|12|11",
        "skuConditionType": "1",
        "skuOfferType": "1",
        "skuCondition": "10050432|10046238| 10050432|10046238| 10036387| 10036553",
        "skuConditionName": "Rs.30 off on buying 2 Tide Naturals 800g",
        "skuConditionQuantity": "1",
        "skuConditionActualPrice": "1900",
        "skuConditionSellingPrice": "2000",
        "discountPercentageValue":"10",
        "discountMax":"100",
        "startDate": "2018/08/12",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Rs. 100 discount on a minimum purchase of Rs. 1000",
        "terms":"Rs. 100 discount on a minimum purchase of Rs. 1000",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup": "42"

    },
    'file_add_coupon_pull_merchant_type_Percentage_discount_on_Bill':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_pull_merchant_type_Percentage_discount_on_Bill':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "1|2|3|4|5|6",
        "couponType": "1",
        "clients[]": ["2","1"],
        "discountType": "PERCENTAGE_DISCOUNT",
        "discountExtraRules": "12",
        "skuConditionType": "1",
        "skuOfferType": "1",
        "discountPercentageValue":"10",
        "discountMax":"100",
        "discountMinBill":"1000",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|3|12|11",
        "title": "10 rs discount on 100 rs bill",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "2",
        "source": "prime",
        "merchant": "6184",
        "startDate": "2018/08/12",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Rs. 100 discount on a minimum purchase of Rs. 1000",
        "terms":"Rs. 100 discount on a minimum purchase of Rs. 1000",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup": "42"

    },
    'file_add_coupon_pull_brand_type_flat_discount':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_pull_brand_type_flat_discount':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "clients[]": ["2","1"],
        "skuConditionType": "1",
        "skuOfferType": "1",
        "discountType": "FLAT_DISCOUNT",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "discountMinBill":"100",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|3|12|11",
        "title": "10_rs_off_on_all_products",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "merchantGroup":"721",
        "brand":"621",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup": "42"

    },
    'file_add_coupon_pull_brand_type_Free_SKUs_on_Bill':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_pull_brand_type_Free_SKUs_on_Bill':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "clients[]": ["2","1"],
        "discountType": "FREE_SKU_WITH_BILL",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "skuOffer": "10036387 |10036553",
        "skuOfferName": "Rs.30 off on buying 2 Tide Naturals 800g",
        "skuOfferQuantity": "1",
        "discountMinBill": "100",
        "skuConditionSellingPrice": "110",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|3|12|11",
        "title": "rin_on_100_rs_purchase",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "merchantGroup":"721",
        "brand":"621",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup": "42"

    },
    'file_add_coupon_pull_brand_type_Free_SKUs_on_SKUs':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_pull_brand_type_Free_SKUs_on_SKUs':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "clients[]": ["2","1"],
        "skuConditionType": "1",
        "skuOfferType": "1",
        "discountType": "FREE_SKU_WITH_SKU",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "skuCondition": "10050432|10046238| 10050432|10046238| 10036387| 10036553",
        "skuOffer":"10050432 | 10046238",
        "skuOfferName":"Tide Bar",
        "skuOfferQuantity":"1",
        "skuConditionName": "Pantene Total Damage Control 80ml",
        "skuConditionQuantity": "2",
        "skuConditionActualPrice": "100",
        "skuConditionSellingPrice": "110",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|3|12|11",
        "title": "1 rin on 1kg ariel",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "merchantGroup":"721",
        "brand":"621",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup": "42"

    },
    'file_add_coupon_pull_brand_type_flat_discount_on_sku':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_pull_brand_type_flat_discount_on_sku':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "clients[]": "2",
        "skuConditionType": "1",
        "skuOfferType": "1",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|202|3|12|11",
        "title": "10rs discount on tide",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "merchantGroup":"721",
        "brand":"621",
        "discountType": "FLAT_DISCOUNT_WITH_SKU",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "skuCondition": "10050432|10046238| 10050432|10046238| 10036387| 10036553",
        "skuConditionName": "Rs.30 off on buying 2 Tide Naturals 800g",
        "skuConditionQuantity": "1",
        "skuConditionActualPrice": "100",
        "skuConditionSellingPrice": "110",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup": "42"

    },
    'file_add_coupon_pull_brand_type_Percentage_discount_on_SKU':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_pull_brand_type_Percentage_discount_on_SKU':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "title": "10% discount on tide",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "merchantGroup":"721",
        "brand":"621",
        "discountType": "PERCENTAGE_DISCOUNT_WITH_SKU",
        "clients[]": ["2","1"],
        "categories": "2|3|12|11",
        "skuConditionType": "1",
        "skuOfferType": "1",
        "skuCondition": "10050432|10046238| 10050432|10046238| 10036387| 10036553",
        "skuConditionName": "Rs.30 off on buying 2 Tide Naturals 800g",
        "skuConditionQuantity": "1",
        "skuConditionActualPrice": "1900",
        "skuConditionSellingPrice": "2000",
        "discountPercentageValue":"10",
        "discountMax":"100",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup": "42"

    },
    'file_add_coupon_pull_brand_type_Percentage_discount_on_Bill':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_pull_brand_type_Percentage_discount_on_Bill':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "title": "10% off on a minimum bill amount of Rs. 500",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "discountType": "PERCENTAGE_DISCOUNT",
        "merchantGroup":"721",
        "brand":"621",
        "clients[]": ["2","1"],
        "categories": "2|3|12|11",
        "skuConditionType": "1",
        "skuOfferType": "1",
        "discountPercentageValue":"10",
        "discountMax":"100",
        "discountMinBill":"1000",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true",
        "userGroup": "42"

    },
    'file_add_coupon_push_brand_type_Free_SKUs_on_Bill':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_push_brand_type_Free_SKUs_on_Bill':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "clients[]": ["2","1"],
        "discountType": "FREE_SKU_WITH_BILL",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "skuOffer": "10036387 |10036553",
        "skuOfferName": "Rs.30 off on buying 2 Tide Naturals 800g",
        "skuOfferQuantity": "1",
        "discountMinBill": "100",
        "skuConditionSellingPrice": "110",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|3|12|11",
        "title": "rin_on_100_rs_purchase",
        "pushType": "1",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "merchantGroup":"721",
        "brand":"621",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "1",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true"
    },
    'file_add_coupon_push_brand_type_flat_discount':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_push_brand_type_flat_discount':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "clients[]": ["2","1"],
        "skuConditionType": "1",
        "skuOfferType": "1",
        "discountType": "FLAT_DISCOUNT",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "discountMinBill":"100",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|3|12|11",
        "title": "10_rs_off_on_all_products",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "merchantGroup":"721",
        "brand":"621",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true"
    },
    'file_add_coupon_push_brand_type_Free_SKUs_on_SKUs':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_push_brand_type_Free_SKUs_on_SKUs':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "clients[]": ["2","1"],
        "skuConditionType": "1",
        "skuOfferType": "1",
        "discountType": "FREE_SKU_WITH_SKU",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "skuCondition": "10050432|10046238| 10050432|10046238| 10036387| 10036553",
        "skuOffer":"10050432 | 10046238",
        "skuOfferName":"Tide Bar",
        "skuOfferQuantity":"1",
        "skuConditionName": "Pantene Total Damage Control 80ml",
        "skuConditionQuantity": "2",
        "skuConditionActualPrice": "100",
        "skuConditionSellingPrice": "110",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|3|12|11",
        "title": "1 rin on 1kg ariel",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "merchantGroup":"721",
        "brand":"621",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true"
    },
    'file_add_coupon_push_brand_type_flat_discount_on_sku':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_push_brand_type_flat_discount_on_sku':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "clients[]": "2",
        "skuConditionType": "1",
        "skuOfferType": "1",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|202|3|12|11",
        "title": "10rs discount on tide",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "merchantGroup":"721",
        "brand":"621",
        "discountType": "FLAT_DISCOUNT_WITH_SKU",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "skuCondition": "10050432|10046238| 10050432|10046238| 10036387| 10036553",
        "skuConditionName": "Rs.30 off on buying 2 Tide Naturals 800g",
        "skuConditionQuantity": "1",
        "skuConditionActualPrice": "100",
        "skuConditionSellingPrice": "110",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true"
    },
    'file_add_coupon_push_brand_type_Percentage_discount_on_SKU':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_push_brand_type_Percentage_discount_on_SKU':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "title": "10% discount on tide",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "merchantGroup":"721",
        "brand":"621",
        "discountType": "PERCENTAGE_DISCOUNT_WITH_SKU",
        "clients[]": ["2","1"],
        "categories": "2|3|12|11",
        "skuConditionType": "1",
        "skuOfferType": "1",
        "skuCondition": "10050432|10046238| 10050432|10046238| 10036387| 10036553",
        "skuConditionName": "Rs.30 off on buying 2 Tide Naturals 800g",
        "skuConditionQuantity": "1",
        "skuConditionActualPrice": "1900",
        "skuConditionSellingPrice": "2000",
        "discountPercentageValue":"10",
        "discountMax":"100",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true"
    },
    'file_add_coupon_push_brand_type_Percentage_discount_on_Bill':{
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
    },
    'data_add_coupon_push_brand_type_Percentage_discount_on_Bill':{
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "0",
        "redeemGender": "MALE",
        "locations": "all",
        "couponType": "2",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "title": "10% off on a minimum bill amount of Rs. 500",
        "pushType": "0",
        "isLimitedRedeem": "true",
        "couponTag": "1",
        "source": "prime",
        "discountType": "PERCENTAGE_DISCOUNT",
        "merchantGroup":"721",
        "brand":"621",
        "clients[]": ["2","1"],
        "categories": "2|3|12|11",
        "skuConditionType": "1",
        "skuOfferType": "1",
        "discountPercentageValue":"10",
        "discountMax":"100",
        "discountMinBill":"1000",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "0",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true"
    },
    'file_add_coupon_push_merchant_type_Free_SKUs_on_Bill': {
        'file': ('A.jpg', open(path1 + '/images/A.jpg', 'rb'), 'image/jpeg'),
    },
    'data_add_coupon_push_merchant_type_Free_SKUs_on_Bill': {
        "redeemDays": "1|2|3|4|5|6|7",
        "redeemMinTime": "0",
        "redeemMaxTime": "24",
        "redeemMinAge": "0",
        "redeemMaxAge": "150",
        "redeemableOnline": "1",
        "isUniversalCode": "1",
        "redeemGender": "MALE",
        "locations": "1|2|3",
        "couponType": "1",
        "clients[]": "2",
        "skuConditionType": "1",
        "skuOfferType": "1",
        "couponStartTime": "2018-08-23T12:41:07.598677",
        "couponEndTime": "2018-08-23T12:41:07.598677",
        "categories": "2|202|3|12|11",
        "title": "Bill Rs. 1000 get a 2kg tide pack",
        "pushType": "1",
        "isLimitedRedeem": "true",
        "couponTag": "3",
        "source": "prime",
        "merchant": "6184",
        "discountType": "FREE_SKU_WITH_BILL",
        "discountExtraRules": "12",
        "discountAbsValue": "10",
        "skuOffer": "10036387 |10036553",
        "skuOfferName": "Rs.30 off on buying 2 Tide Naturals 800g",
        "skuOfferQuantity": "1",
        "discountMinBill": "100",
        "skuConditionSellingPrice": "110",
        "startDate": "2018/08/06",
        "endDate": "2018/08/31",
        "couponUrl": "https://www.google.com",
        "affiliateUrl": "https://www.google.com",
        "description":"Test Coupons Online and physical both",
        "terms":"Test Coupons Online and physical both",
        "couponLabel":"TESTCoupon",
        "couponCode": "$GENERATE_PER_CUSTOMER",
        "redeemCap": "2",
        "maxRedeem": "200",
        "priv": "1",
        "validFrom": "2018/08/06 00:00:00",
        "validTo": "2018/08/31 23:59:00",
        "redeemHours": "0|24",
        "redeemLocation":"1",
        "reductionType":"1",
        "url":"https://www.google.com",
        "redeem-age-interval":"0|150",
        "status":"APPROVE",
        "subscribe":"true"
    },
    'create_segment':
        {"name":"Test123634", "customSegmentId":"TestSiwi3SD","userGroup":"42"},
    'data_create_coupon_group':
        {
            'name': 'grp_test',
            'desc': 'test_group',
            'idList[]': ['6661', '5329', '5334'],
            "userGroup": "42"
        },
    'file_create_coupon_group':
        {
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
        },
    'data_create_brand':
        {
            'name': 'test_brand',
            'desc': 'Test_DESC',
            'externalId': 'Test1234_ID',
            "userGroup": "42"

        },
    'file_create_brand':
        {
        'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')
        },
    'merchant_verify':
            {
                "masId": "21",
                "storeId": "21",

                "tId": "xyzklj199",
                "billAmount": 500,
                "couponCodes": "164F260D",
                "skuData": [
                    {
                        "skuId": "123",
                        "skuQty": 10,
                        "skuPrice": 30
                    },
                    {
                        "skuId": "def",
                        "skuQty": 10,
                        "skuPrice": 20
                    },
                    {
                        "skuId": "def",
                        "skuQty": 10,
                        "skuPrice": 20
                    },
                    {
                        "skuId": "def",
                        "skuQty": 10,
                        "skuPrice": 20
                    },
                    {
                        "skuId": "def",
                        "skuQty": 10,
                        "skuPrice": 20
                    },
                    {
                        "skuId": "def",
                        "skuQty": 10,
                        "skuPrice": 20
                    },
                ]
            },
    'merchant_redeem':
        {
            "couponCodes" : "B90ED539",
            "masId": "1",
            "storeId": "1",
            "tId": "xyzklj199"
        },
    'checkout_coupon_code':
        {
            "masId": "1",
            "storeId": "1",
            "mId": "1",
            "tId": "xyzklj199",
            "billAmount": 100001,
            "couponCodes": "B90ED539",
            "skuData": [
                {
                    "skuId": "123",
                    "skuQty": 10,
                    "skuPrice": 30
                },
                {
                    "skuId": "def",
                    "skuQty": 10,
                    "skuPrice": 20
                },
                {
                    "skuId": "def",
                    "skuQty": 10,
                    "skuPrice": 20
                },
                {
                    "skuId": "def",
                    "skuQty": 10,
                    "skuPrice": 20
                },
                {
                    "skuId": "def",
                    "skuQty": 10,
                    "skuPrice": 20
                },
                {
                    "skuId": "def",
                    "skuQty": 10,
                    "skuPrice": 20
                },
            ]
        },
    'cart_redeem':
        {
            "phone" : "9945240311",
            "masId" : "abhirocks",
            "billAmount" : 1000,
            "skuData" : [
                {
                    "skuId" : "1",
                    "skuQty" : 2,
                    "skuPrice" : 70
                },
                {
                    "skuId" : "2",
                    "skuQty" : 2,
                    "skuPrice" : 30
                },
                {
                    "skuId" : "3",
                    "skuQty" : 2,
                    "skuPrice" : 100
                }
            ]
        }

}


headerType = {
    'None': None,
    'multipartFormDataWithAntiForgery': {
        'x-anti-forgery': "EFgwiLIfwgBda6tWebU9XJt-24-ICUyKJh5JmHJWP9rZ.A3zZHaX9A7lveZrhgL1",
    },
    'applicationJson': {
        'Content-Type': "application/json",
    },
    'multipartFormData' : {
        'content-type': "multipart/form-data",
    },
    'secureJson' :{
        'x-anti-forgery': "0yTkQoQ1LPRbsND93ySSUYu7EOZZ6DyyMwEnyhZWbUL.gmCVB1m6T.SKuQm493Ea",
        "Content-Type": "application/json"
    },
    'redeemApiClientSide' :{
        'Content-Type': "application/x-www-form-urlencoded",
        'Authorization': "Bearer 69600bc2-b3a4-40e3-bc94-60cb1578e909",
        'X-API-Key': "l7xx3e887403b5ed40e78ca8edef65c87587",
        'X-CLIENT-TYPE': "myjio",
    },
    'couponCodeDistributionAPI':{
        'x-client-type': "myjio",
        'x-loginid': "9945240314",
    },
    'CreatCoupons':{
        'X-Anti-Forgery':".Wq0Hv1x-mza6dzTjlIvDzHcan1LFSvKOFYWOWTrvk1UPILfQVzSPLYKG.xzK5JX",
    },
    'latency_coupon':{
        'Authorization': "Basic bDd4eDNlODg3NDAzYjVlZDQwZTc4Y2E4ZWRlZjY1Yzg3NTg3OmM2NDU1NjhhOTI3NzQ1YTY5NmUwZTUyZTU4NzFiZTgz",
    },
    'Category':{
        'Authorization': "Bearer a51cd98e-fcd7-4672-badc-9957ce840fd2",
        'X-API-Key': "l7xx3e887403b5ed40e78ca8edef65c87587",
    },
    'Favourite':{
        'Authorization': "Bearer a51cd98e-fcd7-4672-badc-9957ce840fd2",
        'X-API-Key': "l7xx3e887403b5ed40e78ca8edef65c87587",
    },
    'AllCoupons':{
        'Authorization': "Bearer a51cd98e-fcd7-4672-badc-9957ce840fd2",
        'X-API-Key': "l7xx3e887403b5ed40e78ca8edef65c87587",
        'X-CLIENT-TYPE': "myjio",
    },
    'merchant_verify':{
        'Content-Type': "application/json",
        'x-client-type': "mpos",
    },
    'merchant_redeem':{
        'Content-Type': "application/json",
        'x-client-type': "mpos",
        'x-loginid':"9945240314"
    },
    'get_request_myjio':{
        'Content-Type': "application/json",
        'X-CLIENT-TYPE': "myjio",
        'x-loginID': "9945240311",
    }
}

parameters = {
    'None': None,
    'couponCodeDistributionAPI' : {"version":"v5"},
    'Category':{"client":"myjio","version":"v5"},
    'Favourite':{"version":"v5"},
    'AllCoupons':{"categoryId":"1","start":"0","end":"10","version":"v5","lat":"12.97159","lng":"77.6056679"},
    'GetAllCouponIDFromPromoID':{"endTs":"2018-08-11","startTs":"2018-07-11","status":"approve"},
    'get_merchant_list': {"status": 'approve', 'page-size': '0'},
    # 'get_merchant_detail':{},
    'get_pending_merchant_list': {"status": 'suspended', 'page-size': '0'},
    'get_approved_coupon_list':{'status':'approve', 'page-size':'0', 'page':'0', 'valid':'true'},
    # 'get_coupon_detail':{},
    'get_pending_coupon_list':{'status':'suspend','page-size':'0','page':'0'},
    'get_expired_coupon_list':{'status':'approve','page-size':'0','page':'0','valid':'expired'},
    'get_reliance_retail_pending_list':{'endTs':'2018-09-04','startTs':'2018-08-05','status':'pending'},
    'get_reliance_retail_approved_list':{'endTs':'2018-09-04','startTs':'2018-08-05','status':'approve'},
}

couponDetails = {
    'A' : {
        'name': "Fashion apperals at 25% off",
        'format':'TRENDS',
        'brand_name' : "VANS",
        'image':{'file':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')},
        'category': ["Fashion"],
        'Merchant': ["23332"]
    },
    'B' : {
        'name': "Lotus spa 30% off",
        'brand_name' : "LOTUS HOTELS",
        'format':'TRAVEL',
        'image':{'file':('B.jpg', open( path1 + '/images/B.jpg','rb'), 'image/jpeg')},
        'category': ["Fashion"],
        'Merchant': ["23332"]
    },
    'C' : {
        'name': "Gamezone 25% off",
        'brand_name' : "XBOX one",
        'image':{'file':('C.jpg', open( path1 + '/images/C.jpg','rb'), 'image/jpeg')},
        'category': ["Entertainment"],
        'Merchant': ["10001"]
    },
    'D' : {
        'name': "Dining at Taj at 25% off",
        'brand_name' : "TAJ",
        'format':'TRAVEL',
        'image':{'file':('D.jpg', open( path1 + '/images/D.jpg','rb'), 'image/jpeg')},
        'category': ["Dining"],
        'Merchant': ["6184"]
    },
    'E' : {
        'name': "concert at le-meridian at 25% off",
        'brand_name' : "Le-meridaian",
        'format':'TRAVEL',
        'image':{'file':('E.jpg', open( path1 + '/images/E.jpg','rb'), 'image/jpeg')},
        'category': ["Entertainment"],
        'Merchant': ["10001"]
    },
    'F' : {
        'name': "Brunch at little Italy at 25% off",
        'brand_name' : "Little Italy",
        'format':'TRAVEL',
        'image':{'file':('F.jpg', open( path1 + '/images/F.jpg','rb'), 'image/jpeg')},
        'category': ["Dining"],
        'Merchant': ["6184"]
    },
    'G' : {
        'name': "Zoom at Zoom Car at 30% off",
        'brand_name' : "ZOOM Car",
        'format':'TRAVEL',
        'image':{'file':('G.jpg', open( path1 + '/images/G.jpg','rb'), 'image/jpeg')},
        'category': ["Travel"],
        'Merchant': ["6184"]
    },
    'H' : {
        'name': "Riding gears at 35% off",
        'brand_name' : "Royal Enfield",
        'format':'TRENDS',
        'image':{'file':('H.jpg', open( path1 + '/images/H.jpg','rb'), 'image/jpeg')},
        'category': ["Fashion"],
        'Merchant': ["23332"]
    },
    'I' : {
        'name': "Fashion apperals for winters at 35% off",
        'brand_name' : "Marisma",
        'format':'TRENDS',
        'image':{'file':('I.jpg', open( path1 + '/images/I.jpg','rb'), 'image/jpeg')},
        'category': ["Fashion"],
        'Merchant': ["23332"]
    },
    'J' : {
        'name': "dining with style at 25% off",
        'brand_name' : "Barbeque Nation",
        'format':'TRAVEL',
        'image':{'file':('J.jpg', open( path1 + '/images/J.jpg','rb'), 'image/jpeg')},
        'category': ["Dining"],
        'Merchant': ["6184"]
    },
    'K' : {
        'name': "Gadgets with great discounts",
        'brand_name' : "Royal Enfield",
        'format':'TRAVEL',
        'image':{'file':('K.jpg', open( path1 + '/images/K.jpg','rb'), 'image/jpeg')},
        'category': ["Fashion"],
        'Merchant': ["23332"]
    },
    'L' : {
        'name': "A flamy night at Radison hotels 25% off",
        'brand_name' : "Hotel Radision",
        'format':'TRAVEL',
        'image':{'file':('L.jpg', open( path1 + '/images/L.jpg','rb'), 'image/jpeg')},
        'category': ["Dining"],
        'Merchant': ["6184"]
    },
    'M' : {
        'name': "Be at the top at 25% travel offer for Dubai off",
        'brand_name' : "Yatra",
        'format':'TRAVEL',
        'image':{'file':('M.jpg', open( path1 + '/images/M.jpg','rb'), 'image/jpeg')},
        'category': ["Travel"],
        'Merchant': ["23596"]
    },

}

merchant_details = {
    'A': {
        'image':{'image':('A.jpg', open( path1 + '/images/A.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "reliance smart"
    },
    'B' : {
        'image':{'image':('B.jpg', open( path1 + '/images/B.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "Ashwarya grocery"
    },
    'C' : {
        'image':{'image':('C.jpg', open( path1 + '/images/C.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "spencer's"
    },
    'D' : {
        'image':{'image':('D.jpg', open( path1 + '/images/D.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "tantra"
    },
    'E' : {
        'image':{'image':('E.jpg', open( path1 + '/images/E.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "mustard"
    },
    'F' : {
        'image':{'image':('F.jpg', open( path1 + '/images/F.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "W"
    },
    'G' : {
        'image':{'image':('G.jpg', open( path1 + '/images/G.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "sony world"
    },
    'H' : {
        'image':{'image':('H.jpg', open( path1 + '/images/H.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "west side"
    },
    'I' : {
        'image':{'image':('I.jpg', open( path1 + '/images/I.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "croma"
    },
    'J' : {
        'image':{'image':('J.jpg', open( path1 + '/images/J.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "spar"
    },
    'K' : {
        'image':{'image':('K.jpg', open( path1 + '/images/K.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "RELIANCE DIGITAL"
    },
    'L' : {
        'image':{'image':('L.jpg', open( path1 + '/images/L.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "lo'real"
    },
    'M' : {
        'image':{'image':('M.jpg', open( path1 + '/images/M.jpg','rb'), 'image/jpeg')},
        'merchant_name' : "la-femme"
    },

}

sku_data = {
    'A': {'billAmount': 1000,
          'sku_data': [{"skuId": "10050432", "skuQty": 1, "skuPrice": 30},
                    {"skuId": "10146238", "skuQty": 2, "skuPrice": 10},
                    {"skuId": "10050432", "skuQty": 2, "skuPrice": 20},
                    {"skuId": "10046238", "skuQty": 3, "skuPrice": 10},
                    {"skuId": "10036387", "skuQty": 4, "skuPrice": 20},
                    {"skuId": "10036553", "skuQty": 3, "skuPrice": 30}],
          'sku_id_lst': "10050432|10146238|10046238| 10036387| 10036553"
          },
    'B': {'billAmount': 600,
          'sku_data': [{"skuId": "10050432", "skuQty": 1, "skuPrice": 30},
                      {"skuId": "10146238", "skuQty": 2, "skuPrice": 10},
                      {"skuId": "10046238", "skuQty": 3, "skuPrice": 10},
                      {"skuId": "10036387", "skuQty": 4, "skuPrice": 20}],
          'sku_id_lst': "10050432|10146238| 10046238| 10036387"
          },
    'C': {'billAmount': 800,
          'sku_data': [{"skuId": "10050432", "skuQty": 1, "skuPrice": 30},
                      {"skuId": "10046238", "skuQty": 3, "skuPrice": 10},
                      {"skuId": "10036387", "skuQty": 4, "skuPrice": 20},
                      {"skuId": "10036553", "skuQty": 3, "skuPrice": 30}],
          'sku_id_lst': "10050432|10046238| 10036387| 10036553"
          },
    'D': {'billAmount': 1000,
          'sku_data': [{"skuId": "10050432", "skuQty": 1, "skuPrice": 30},
                      {"skuId": "10146238", "skuQty": 2, "skuPrice": 10},
                      {"skuId": "10050432", "skuQty": 2, "skuPrice": 20},
                      {"skuId": "10046238", "skuQty": 3, "skuPrice": 10},
                      {"skuId": "10036387", "skuQty": 4, "skuPrice": 20},
                      {"skuId": "10036553", "skuQty": 3, "skuPrice": 30}],
          'sku_id_lst': "10050432|10146238|10046238| 10036387| 10036553|10050432"
          },
    'E': {'billAmount': 300,
          'sku_data': [{"skuId": "10050432", "skuQty": 1, "skuPrice": 30},
                      {"skuId": "10146238", "skuQty": 2, "skuPrice": 10},
                      {"skuId": "10046238", "skuQty": 3, "skuPrice": 10},
                      {"skuId": "10036387", "skuQty": 4, "skuPrice": 20},
                      {"skuId": "10036553", "skuQty": 3, "skuPrice": 30}],
          'sku_id_lst': "10050432|10146238|10046238| 10036387| 10036553"
          },
    'F': {'billAmount': 700,
          'sku_data': [{"skuId": "10050432", "skuQty": 1, "skuPrice": 30},
                      {"skuId": "10050432", "skuQty": 2, "skuPrice": 20},
                      {"skuId": "10046238", "skuQty": 3, "skuPrice": 10},
                      {"skuId": "10036387", "skuQty": 4, "skuPrice": 20},
                      {"skuId": "10036553", "skuQty": 3, "skuPrice": 30}],
          'sku_id_lst': "10050432|10046238| 10036387| 10036553|10050432"
          },
}

# sku_data = {
#     'A': {'billAmount': 1000,
#           'sku_data': [{"skuId": "10050432", "skuQty": 1, "skuPrice": 30},
#                     ],
#           'sku_id_lst': "10050432"
#           },
#     'B': {'billAmount': 600,
#           'sku_data': [{"skuId": "10050432", "skuQty": 1, "skuPrice": 30},
#                        ],
#           'sku_id_lst': "10050432"
#           },
#     'C': {'billAmount': 800,
#           'sku_data': [{"skuId": "10050432", "skuQty": 1, "skuPrice": 30},
#                        ],
#           'sku_id_lst': "10050432"
#           },
#     'D': {'billAmount': 1000,
#           'sku_data': [{"skuId": "10050432", "skuQty": 1, "skuPrice": 30},
#                        ],
#           'sku_id_lst': "10050432"
#           },
#     'E': {'billAmount': 300,
#           'sku_data': [{"skuId": "10050432", "skuQty": 1, "skuPrice": 30},
#                        ],
#           'sku_id_lst': "10050432"
#           },
#     'F': {'billAmount': 700,
#           'sku_data': [{"skuId": "10046238", "skuQty": 1, "skuPrice": 30},
#                        ],
#           'sku_id_lst': "10046238"
#           },
# }